version: '3.8'

services:

  ai_db:
    container_name: ai_db_cn
    image: postgres:latest
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dW7yV6gN6mR3
      POSTGRES_DB: oneapi
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - lan
    volumes: 
      - /var/ai/psql/data:/var/lib/postgresql/data/pgdata
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        
  ai_newapi:
    container_name: ai_newapi_cn
    image: calciumion/new-api:latest
    networks: 
      - lan
    depends_on:
      - ai_db
    ports:
      - "3008:3000"
    environment:
      TZ: Asia/Shanghai
      SQL_DSN: postgres://root:dW7yV6gN6mR3@ai_db:5432/oneapi
    volumes:
      - /var/ai/newapi/data:/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  ai_openwebui: 
    container_name: ai_openwebui_cn
    image: ghcr.nju.edu.cn/open-webui/open-webui:main
    volumes: 
      - /var/ai/openwebui/data:/app/backend/data
    ports:
      - "3001:8080"
    environment:
      - HF_ENDPOINT=https://hf-mirror.com/
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  ai_nextchat:
    container_name: ai_nextchat_cn
    image: yidadaa/chatgpt-next-web
    ports:
      - "3002:3000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        
networks:
  lan: